### ISSUE TITLE
Add pre-commit hook to use coverage badge with pre-commit

### ISSUE THREAD

**Issue by Husain-Kapadia** [dbrgn/coverage-badge#11]
Can you add a pre-commit hook to the repo so that it can also be used with pre-commit https://github.com/pre-commit/pre-commit-hooks

**Comment by dbrgn** [comment]
I'm not sure what that would entail, but right now I don't plan to add any new features.

A PR that doesn't significantly increase maintenance effort would probably be merged though.

**Comment by Husain-Kapadia** [comment]
I would like the coverage-badge to update every time I make a new commit. I do not use as my travis-ci-cd tool. I tried integrating this with teamcity's ci tool but ran into many issues which were related to teamcity. So, I thought it would be useful for that.

**Comment by dbrgn** [comment]
In that case you can set up your own pre-commit hook that calls coverage and coverage-badge, right?

**Comment by Husain-Kapadia** [comment]
I faced some problems doing that locally. 

I feel it would be best if this repository had a `.pre-commit-hooks.yaml` like how it is in `Black` for example, https://github.com/psf/black/blob/main/.pre-commit-hooks.yaml.
