### ISSUE TITLE
Push Coverage 6.x compatible Release

### ISSUE THREAD

**Issue by didorothy** [dbrgn/coverage-badge#19]
I have noticed that the change to allow for Coverage 6.x was merged but no release was made to pypi.

Would it be possible to get a new release published soon?

I apologize if I have missed docs about a regular release schedule. 

Thanks.

**Comment by dbrgn** [comment]
You're right, I missed that! I'll push a new release tonight.

**Comment by dbrgn** [comment]
v1.1.0 is out.
