### ISSUE TITLE
Update README.rst with test coverage badge.

### ISSUE THREAD

**Issue by jkatzer** [dbrgn/coverage-badge#2]

**Comment by dbrgn** [comment]
I don't currently have set up a server that hosts these generated badges. Travis would have to upload it to somewhere.

But in the case of Travis, you could simply use a tool like coveralls, which makes this module unnecessary. I primarily wrote it for internal CI systems like Jenkins.

But if you have an idea where to upload the badge, I can implement the request :)

**Comment by jkatzer** [comment]
@dbgrn thanks for the quick response. i just ran into the issue today of trying to embed an `.svg` into a `README.md` on github. its blocked now to prevent XSS attacks that browsers have already fixed. i am going to convert the badge to png and try again.

Excerpt from current `Makefile`
```
test-coverage:
	py.test --cov=product_parser

update-coverage: test-coverage
	coverage-badge -o coverage-badge.svg
```

**Comment by jkatzer** [comment]
@dbgrn thanks for the quick response. i just ran into the issue today of trying to embed an `.svg` into a `README.md` on github. its blocked now to prevent XSS attacks that browsers have already fixed. i am going to convert the badge to png and try again.

Excerpt from current `Makefile`
```
test-coverage:
	py.test --cov=product_parser

update-coverage: test-coverage
	coverage-badge -o coverage-badge.svg
```

**Comment by dbrgn** [comment]
You could use a tool like `convert` (part of imagemagick) to convert the SVG to PNG.

**Comment by jkatzer** [comment]
I love this badge thing so much, I might make a PR with an optional dependency on PIL/Pillow to get a png.

-jason
Dictated by Siri

**Comment by dbrgn** [comment]
Thanks! :) But honestly I'm not sure if I'd want to merge that, as it's an additional dependency (right now there are none, so you can just copy-paste the script) and SVG can be embedded almost universally. The only place where SVG seems to be problematic is Github, and most people will probably use Travis on Github.

If you have any other improvements, let me know. But I think the use case of getting a PNG is best served with imagemagick or similar tools.

**Comment by jkatzer** [comment]
@dbrgn it would be an optional dependency. a good example (as always) is [requests.py](http://docs.python-requests.org/en/master/):
* [setup.py-extras_require](https://github.com/kennethreitz/requests/blob/master/setup.py#L94-L97)
* [SO of how to pip install extras](http://stackoverflow.com/questions/31811949/pip-install-requestssecurity-vs-pip-install-requests-difference)

so a user would `pip install coverage-badge[png]` to get png support, and would otherwise get an error that they need to do so.

**Comment by dbrgn** [comment]
Sounds good. I assume if the user uses an old pip version without extras support, then the extra will simply not be installed?

In any case, feel free to submit a PR. But only if it's based on conversion of the SVG. Otherwise I'd have to maintain two parallel ways of generating the badge, which I want to avoid as there's little gain :)
