### ISSUE TITLE
displaying svg file badge in readme.md

### ISSUE THREAD

**Issue by BouchaaraAdil** [dbrgn/coverage-badge#5]
hi, i want to display the svg file badge in readme file, so i used rawgit.com for converting the file,
 it gived me an error when the file get parsed, is there another way to get coverage badge displayed in readme.md

**Comment by dbrgn** [comment]
It works for me.

https://cdn.rawgit.com/dbrgn/coverage-badge/master/media/15.svg

![img](https://cdn.rawgit.com/dbrgn/coverage-badge/master/media/15.svg)
