### ISSUE TITLE
Extending the scope

### ISSUE THREAD

**Issue by smarie** [dbrgn/coverage-badge#7]
This is a great and useful package ! 

For internal and public projects I had to create similar commands for pytest test results and flake8 analysis results.

About to create dedicated libraries, I think that it would probably be wiser to put all of these as subcommands of a single badge generator.

Would you agree ? If so I can propose some PR where we would move from argparse to click and where you would have subcommands for each kind of badge to generate.

We would also have to rename the package to something more general such as `makebadge` or `genbadge`.

The result would look like:

```
genbadge coverage -o <file.svg> ...
genbadge flake8 -o <file.svg> ...
genbadge pytest -o <file.svg> ...
```

**Comment by dbrgn** [comment]
Hi, thanks for the proposal. It does sound useful, however I currently lack the capacity and motivation to give this project proper maintenance. Therefore I'd prefer not to enlarge it's scope even more.

> where we would move from argparse to click

While I'm a fan of click, this script currently does not have any dependencies outside of the stdlib, so it can be copy-pasted to a CI config without any packaging issues. I think that's a big advantage and would prefer to keep it that way (even if it means that the API is a bit less ergonomic / modern).

> We would also have to rename the package to something more general such as makebadge or genbadge.

That sounds sensible. I think the best path forward for now would be if you'd fork / copy this project, do the desired changes yourself and publish a package under the new name. Feel free to ping me again afterwards, I think I could add a link to your fork for the people that want more than just `coverage` support.

Does that sound good to you?

**Comment by smarie** [comment]
Hi @dbrgn this makes sense and I value your honesty here. I'll keep you posted when I make that move then.

Concerning `click`, I am totally in line with you. However to handle subcommands I'd rather start with it to ship faster a first release, and then wait for an argparse expert to submit a PR able to drop that dependency :)

**Comment by dbrgn** [comment]
I'm not an expert at all, but argparse does subcommands through subparsers: https://docs.python.org/3.5/library/argparse.html#sub-commands

Great, then I'll close this issue for now. Just ping me if you have something out :slightly_smiling_face:

**Comment by smarie** [comment]
Hello @dbrgn , I finally found some time to make the library I was telling you about. Here it is: https://smarie.github.io/python-genbadge/

As you can see, this is a generalization of the concept, with support for pytest results, coverage, as well as flake8. I try to depend as little as possible on the tools themselves when there is a standard format (e.g. junit.xml, coverage.xml).

Do not hesitate to let me know your thoughts about it !

**Comment by dbrgn** [comment]
@smarie cool, I added a link to it to the README! https://github.com/dbrgn/coverage-badge

**Comment by smarie** [comment]
This is very nice of you, thanks @dbrgn  !
