### ISSUE TITLE
Licence file is missing

### ISSUE THREAD

**Issue by Hoxbro** [dbrgn/coverage-badge#8]
I am trying to add you package to [conda-forge](https://github.com/conda-forge/staged-recipes/pull/11991), but I need to add a license file which I can´t find it in the repo.

**Comment by dbrgn** [comment]
Good point, seems I forgot about that one :slightly_smiling_face:

**Comment by dbrgn** [comment]
Fixed in 6e28f8634bfea9d114c954a449806490f43cb3dd
